version: "3.3"

services:
  yolo:
    build: ./yolo-client
    container_name: yolo
    volumes:
      - ./yolo-client:/workspace
    stdin_open: true
    tty: true
    ports:
     - 4008:4008
  
  gst-container:
    build: ./gstreamer-sandbox/src
    container_name: gst-container
    volumes:
      - ./gstreamer-sandbox/src:/workspace
    stdin_open: true
    tty: true
